[localhost]
localhost ansible_connection=local

[Zabbix]
zabbix-one ansible_host=10.0.1.4 fixed_ip=10.0.1.4 ansible_user=ubuntu
zabbix-two ansible_host=10.0.1.11 fixed_ip=10.0.1.11 ansible_user=ubuntu
zabbix-db ansible_host=10.0.1.6 fixed_ip=10.0.1.6 ansible_user=ubuntu
Ansible-Center ansible_host=194.47.155.121 fixed_ip=10.0.1.7 floating_ip=194.47.155.121 ansible_user=ubuntu
