[local]
localhost ansible_connection=local

[zabbix]
zabbix-one ansible_host=10.0.1.11 ansible_user=ubuntu
zabbix-two ansible_host=10.0.1.21 ansible_user=ubuntu
zabbix-db ansible_host=10.0.1.23 ansible_user=ubuntu

[zabbix:vars]
ansible_ssh_private_key_file=~/.ssh/ansible

[ansible_center]
ansible-center ansible_host=194.47.155.129 ansible_user=ubuntu
