[localhost]
localhost ansible_connection=local

[Zabbix]
zabbix-one ansible_host=1.1.1.1 fixed_ip=1.1.1.1 ansible_user=ubuntu ansible_ssh_common_args='-o ProxyJump=ansible-center'
zabbix-two ansible_host=1.1.1.1 fixed_ip=1.1.1.1 ansible_user=ubuntu ansible_ssh_common_args='-o ProxyJump=ansible-center'
zabbix-db ansible_host=1.1.1.1 fixed_ip=1.1.1.1 ansible_user=ubuntu ansible_ssh_common_args='-o ProxyJump=ansible-center'

[Zabbix:vars]
ansible_ssh_private_key_file=~/.ssh/ansible

[ansible_center]
ansible-center ansible_host=1.1.1.1 fixed_ip=1.1.1.1 floating_ip=1.1.1.1 ansible_user=ubuntu
