- hosts: localhost
  tasks:
  
    #################################################
    # CLEANUP / FRESH START
    #################################################
    - name: Delete Zabbix-One
      openstack.cloud.server:
        state: absent
        name: Zabbix-One
        delete_ips: true
      ignore_errors: true
      
    - name: Delete Zabbix-Two
      openstack.cloud.server:
        state: absent
        name: Zabbix-Two
        delete_ips: true
      ignore_errors: true

    - name: Delete Zabbix-Db
      openstack.cloud.server:
        state: absent
        name: Zabbix-Db
        delete_ips: true
      ignore_errors: true

    - name: Delete Ansible-Center
      openstack.cloud.server:
        state: absent
        name: Ansible-Center
        delete_ips: true
      ignore_errors: true

    - name: Get all floating IPs
      openstack.cloud.floating_ip_info:
      register: floating_ips
      
    - debug:
        var: floating_ips

    - name: Delete all floating IPs
      command: >
        openstack floating ip delete {{ item.id }}
      loop: "{{ floating_ips.floating_ips }}"

    - name: Get all ports
      openstack.cloud.port_info:
      register: ports
      
    - debug:
        var: ports
      
    - name: Delete VM ports
      openstack.cloud.port:
        state: absent
        id: "{{ item.id }}"
      loop: "{{ ports.ports }}"
      when: item.device_owner == "compute:nova"
      ignore_errors: true

    - name: Remove router interfaces
      openstack.cloud.router:
        state: absent
        name: PRIMA-ROUTER
        interfaces:
          - PRIMA-SUB
      ignore_errors: true
      
    - name: Remove router
      openstack.cloud.router:
        state: absent
        name: PRIMA-ROUTER 
      ignore_errors: true
      
    - name: Remove router
      openstack.cloud.router:
        state: absent
        name: PRIMA-ROUTER-INT
      ignore_errors: true

    - name: Remove router
      openstack.cloud.router:
        state: absent
        name: PRIMA-ROUTER-EXT
      ignore_errors: true

    - name: Wait for router cleanup propagation
      pause:
        seconds: 10

    - name: Remove router
      openstack.cloud.router:
        state: absent
        name: PRIMA-ROUTER 
      ignore_errors: true

    - name: Remove subnet
      openstack.cloud.subnet:
        state: absent
        name: PRIMA-SUB
      ignore_errors: true

    - name: Remove subnet
      openstack.cloud.subnet:
        state: absent
        name: PRIMA-SUB
      ignore_errors: true

    - name: Remove subnet
      openstack.cloud.subnet:
        state: absent
        name: PRIMA-SUB-INT
      ignore_errors: true

    - name: Remove subnet
      openstack.cloud.subnet:
        state: absent
        name: PRIMA-SUB-EXT
      ignore_errors: true

    - name: Remove network
      openstack.cloud.network:
        state: absent
        name: PRIMA-NET-INTERNAL
      ignore_errors: true

    - name: Remove network
      openstack.cloud.network:
        state: absent
        name: PRIMA-NET-EXTERNAL
      ignore_errors: true

    - name: Remove security group
      openstack.cloud.security_group:
        state: absent
        name: PRIMA-SG
      ignore_errors: true
      
    - name: Remove keypair
      openstack.cloud.keypair:
        state: absent
        name: PRIMA-KEY
      ignore_errors: true
         
    #################################################
    # CREATE NEW RESOURCES
    #################################################
    - name: List networks
      openstack.cloud.networks_info:
      register: result

    - debug:
        var: result

    - name: Create network
      openstack.cloud.network:
        state: present
        name: PRIMA-NET
               
    - name: Create subnet
      openstack.cloud.subnet:
        state: present
        network_name: PRIMA-NET
        name: PRIMA-SUB
        ip_version: 4
        cidr: "{{ PRIMA_SUBNET_CIDR }}"
        enable_dhcp: true
        gateway_ip: "{{ PRIMA_GATEWAY_IP }}"
        dns_nameservers:
          - 8.8.8.8
    
    - name: Create EXT router (gateway -> External)
      openstack.cloud.router:
        state: present
        name: PRIMA-ROUTER-EXT
        network: External          
        interfaces:
          - net: PRIMA-NET 
            subnet: PRIMA-SUB
            portip: "{{ PRIMA_GATEWAY_IP }}"

    - name: Create INT router (Gateway -> Internal)
      openstack.cloud.router:
        state: present
        name: PRIMA-ROUTER-INT
        network: Internal          
        interfaces:
          - net: PRIMA-NET 
            subnet: PRIMA-SUB
            portip: "{{ PRIMA_ROUTER_INT_IP }}"
            
    - name: Create security group
      openstack.cloud.security_group:
        state: present
        name: PRIMA-SG
        
    - name: Allow SSH
      openstack.cloud.security_group_rule:
        security_group: PRIMA-SG
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_ip_prefix: 0.0.0.0/0
       
    - name: Allow all TCP within security group
      openstack.cloud.security_group_rule:
        security_group: PRIMA-SG
        protocol: tcp
        #port_range_min: 3306
        #port_range_max: 3306
        remote_group: PRIMA-SG
        
    - name: Allow all ICMP within security group
      openstack.cloud.security_group_rule:
        security_group: PRIMA-SG
        protocol: icmp
        remote_group: PRIMA-SG   
  
    - name: Upload keypair to OpenStack
      openstack.cloud.keypair:
        state: present
        name: PRIMA-KEY
        public_key_file:  "{{ playbook_dir }}/PUBLIC_KEYS/ansible.pub"
      
    - name: Install SSH private key
      copy:
        src: "{{ playbook_dir }}/PRIVATE_KEYS/ansible.pem"
        dest: "{{ lookup('env','HOME') }}/.ssh/ansible"
        mode: '0600'
      delegate_to: localhost
 
    - name: Install SSH public key
      copy:
        src:  "{{ playbook_dir }}/PUBLIC_KEYS/ansible.pub"
        dest: "{{ lookup('env','HOME') }}/.ssh/ansible.pub"
        mode: '0600'
      delegate_to: localhost 
 
    #################################################
    # CREATE NEW VMS
    #################################################
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    
    - name: Reset Zabbix host list
      set_fact:
        zabbix_hosts: []
    
    - name: Create VM 1
      openstack.cloud.server:
        state: present
        name: Zabbix-One
        image: Ubuntu 24.04
        flavor: small
        network: PRIMA-NET
        key_name: PRIMA-KEY
        security_groups:
          - PRIMA-SG
        auto_ip: false
        terminate_volume: true
      register: vm
  
    - name: Get IP
      set_fact:
        vm_ip: "{{ vm.server.addresses['PRIMA-NET'][0].addr }}"
     
    - name: Add VM1 to list
      set_fact:
        zabbix_hosts: "{{ zabbix_hosts + [ { 
          'name': 'zabbix-one',
          'ip': vm_ip, 
          'floating_ip': floating_ip | default(''),
          'access_ip': floating_ip | default(vm_ip)
        }] }}"
              
    - name: Create VM 2
      openstack.cloud.server:
        state: present
        name: Zabbix-Two
        image: Ubuntu 24.04
        flavor: small
        network: PRIMA-NET      
        key_name: PRIMA-KEY
        security_groups:
          - PRIMA-SG
        auto_ip: false
        terminate_volume: true
      register: vm
  
    - name: Get IP
      set_fact:
        vm_ip: "{{ vm.server.addresses['PRIMA-NET'][0].addr }}"
     
    - name: Add VM2 to list
      set_fact:
        zabbix_hosts: "{{ zabbix_hosts + [ { 
          'name': 'zabbix-two',
          'ip': vm_ip, 
          'floating_ip': floating_ip | default(''),
          'access_ip': floating_ip | default(vm_ip)
        }] }}"
         
    - name: Create VM DB
      openstack.cloud.server:
        state: present
        name: Zabbix-Db
        image: Ubuntu 24.04
        flavor: small
        network: PRIMA-NET
        key_name: PRIMA-KEY
        security_groups:
          - PRIMA-SG
        auto_ip: false
        terminate_volume: true
      register: vm
  
    - name: Get IP
      set_fact:
        vm_ip: "{{ vm.server.addresses['PRIMA-NET'][0].addr }}"

    - name: Debug VM IP
      debug:
        var: vm_ip
     
    - name: Add VM3 to list
      set_fact:
        zabbix_hosts: "{{ zabbix_hosts + [ { 
          'name': 'zabbix-db',
          'ip': vm_ip, 
          'floating_ip': floating_ip | default(''),
          'access_ip': floating_ip | default(vm_ip)
        }] }}"
        
    - name: Create VM 4
      openstack.cloud.server:
        state: present
        name: Ansible-Center
        image: Ubuntu 24.04
        flavor: small
        network: PRIMA-NET
        key_name: PRIMA-KEY
        security_groups:
          - PRIMA-SG
        auto_ip: true
        terminate_volume: true
      register: vm
  
    - name: Get IP
      set_fact:
        vm_ip: "{{ vm.server.addresses['PRIMA-NET'][0].addr }}"
    
    - name: Wait for floating IP association
      pause:
        seconds: 10
        
    - name: Get floating IPs
      openstack.cloud.floating_ip_info:
      register: floating_ips

    - name: Extract floating IP
      set_fact:
        floating_ip: >-
          {{
            (
              floating_ips.floating_ips
              | selectattr('fixed_ip_address', 'equalto', vm_ip)
              | map(attribute='floating_ip_address')
              | first
            ) | default('')
          }}
      
    - name: Add VM4 to list
      set_fact:
        zabbix_hosts: "{{ zabbix_hosts + [ { 
          'name': 'ansible-center',
          'ip': vm_ip, 
          'floating_ip': floating_ip | default(''),
          'access_ip': floating_ip | default(vm_ip)
        }] }}"
 
    - name: Extract ansible-center floating IP
      set_fact:
        ansible_center_floating_ip: >-
          {{
            zabbix_hosts
            | selectattr('name', 'equalto', 'ansible-center')
            | map(attribute='floating_ip')
            | first
          }}
 
    - name: Write inventory.ini
      template:
        src: ../templates/inventory.ini.j2
        dest: "{{ playbook_dir }}/../inventory.ini"
        mode: '0600'
        force: true
        
    #################################################
    # Create SSH Config
    #################################################  
    
    #Hosts
    - name: Find ansible-center
      set_fact:
        ansible_center: "{{ (zabbix_hosts | selectattr('name','equalto','ansible-center') | first) }}"
        
    - name: Get worker hosts
      set_fact:
        worker_hosts: "{{ zabbix_hosts | rejectattr('name','equalto','ansible-center') | list }}"    

    - name: Generate SSH config (Hosts)
      template:
        src:  ../templates/ssh_config.j2
        dest: "{{ playbook_dir }}/../ssh_config"
        mode: '0600'
        
    #Nodes
    - name: Generate SSH config (Nodes)
      template:
        src:  ../templates/ssh_config_nodes.j2
        dest: "{{ playbook_dir }}/../ssh_config_nodes"
        mode: '0600'

